"""empty message

Revision ID: 8c920a647202
Revises: 58d80fa347cd
Create Date: 2018-07-27 17:30:05.341008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c920a647202'
down_revision = '58d80fa347cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tags')
    op.drop_table('entries')
    op.drop_constraint(None, 'tag__map', type_='foreignkey')
    op.drop_constraint(None, 'tag__map', type_='foreignkey')
    op.create_foreign_key(None, 'tag__map', 'entry', ['entry_id'], ['id'])
    op.create_foreign_key(None, 'tag__map', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag__map', type_='foreignkey')
    op.drop_constraint(None, 'tag__map', type_='foreignkey')
    op.create_foreign_key(None, 'tag__map', 'entries', ['entry_id'], ['id'])
    op.create_foreign_key(None, 'tag__map', 'tags', ['tag_id'], ['id'])
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.drop_table('entry')
    op.drop_table('tag')
    # ### end Alembic commands ###
